### ISSUE TITLE
Improvement for comparison operator

### ISSUE THREAD

**Issue by jube** [j-jorge/counting-in-cpp#4]
In section "2.5.12 Hash tables", you write a comparison operator for `color`. There is a better (and more safe) way to do it:

```cpp
bool operator<(const color& that) const {
  std::tie(red, green, blue) < std::tie(that.red, that.green, that.blue);
}
```

`std::tie` creates a `std::tuple` which already implements `operator<` with lexicographical order.

You do not talk about `std::tie` but it's the C++11 way of doing structured binding. It's a very good alternative to `std::get`.

**Comment by j-jorge** [comment]
Thanks for the suggestion :) I have added a few words about `std::tie` in the section about tuples but I kept the comparison operator as is, as I think using `std::tie` here adds another layer of complexity, and these examples are here to show the pre C++11 way.
