### ISSUE TITLE
Navigation in web version

### ISSUE THREAD

**Issue by joshka** [j-jorge/counting-in-cpp#8]
Hi there, great resource for someone re-learning modern C++. Some quick feedback that I hope you don't mind. As a reader I found two things that made me switch to the PDF version over the web version:

1. The amount of text before having to hit next is often a too little because the structure emphasizes the full tree of the doc (e.g. https://julien.jorge.st/counting-in-cpp/counting-in-c++ch3.html and https://julien.jorge.st/counting-in-cpp/counting-in-c++se8.html#x13-120002.1 and https://julien.jorge.st/counting-in-cpp/counting-in-c++su1.html#x14-14000)
2. Related to the first point, going from one page to the next page is often difficult as the reader has to navigate up then across the tree. E.g. try navigating just using links from the last page of chapter 2 (or is it 3) to the first of 3(4?) https://julien.jorge.st/counting-in-cpp/counting-in-c++su43.html#x61-1280002.6.9 to https://julien.jorge.st/counting-in-cpp/counting-in-c++su1.html#x14-130002.1.1

Incidentally the chapter numbers don't match the URL.

Some possible fixes:
1. Add a next link that goes to the next page in DFS order
2. Combine the full section (e.g. 2.1) instead of showing the individual pages (e.g. 2.1.1),

**Comment by j-jorge** [comment]
Thanks for the comment and suggestions, it is much appreciated.

I use `make4ht` to convert the LaTeX files into HTML and I do not know if I have the level of control for your suggestions, but I will look into it as soon as I find some time :)
